// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCC.Db;

#nullable disable

namespace TCC.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221209210112_identity5")]
    partial class identity5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TCC.Areas.Identity.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8d98042-6a72-42ac-b44d-f9aaea03413a",
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(753),
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Eduardo",
                            Password = "12345",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f676ecbb-4e06-48c5-925c-7f9bbc00a5c5",
                            TwoFactorEnabled = false,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c333de2-65d6-451d-b81b-a57420f2ae5c",
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(771),
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Paulo",
                            Password = "54321",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8397620c-e8dd-4440-aa3a-b5b25b3f5a65",
                            TwoFactorEnabled = false,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("TCC.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 2000.0,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(947),
                            IconId = 1,
                            Name = "Conta corrente",
                            UserId = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Balance = 233.33000000000001,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(949),
                            IconId = 2,
                            Name = "Conta PJ",
                            UserId = 2,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("TCC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasDiscriminator<string>("Type").HasValue("Category");
                });

            modelBuilder.Entity("TCC.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<double>("CurrentBalance")
                        .HasColumnType("double");

                    b.Property<double>("FinalBalance")
                        .HasColumnType("double");

                    b.Property<DateTime>("FinalDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1048),
                            CurrentBalance = 400.0,
                            FinalBalance = 2000.0,
                            FinalDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconId = 1,
                            IsCompleted = false,
                            IsDeleted = false,
                            Name = "Viagem",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1050),
                            CurrentBalance = 12000.32,
                            FinalBalance = 35000.720000000001,
                            FinalDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconId = 2,
                            IsCompleted = false,
                            IsDeleted = false,
                            Name = "Carro",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TCC.Models.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Icons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageName = "img1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImageName = "img2.jpg"
                        });
                });

            modelBuilder.Entity("TCC.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasDiscriminator<string>("Type").HasValue("Transaction");
                });

            modelBuilder.Entity("TCC.Models.Expense", b =>
                {
                    b.HasBaseType("TCC.Models.Transaction");

                    b.Property<bool>("isPaid")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("Expense");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Category = 13,
                            CategoryId = 1,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1013),
                            Description = "Mercado",
                            TransactionDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1013),
                            UserId = 1,
                            Value = 250.0,
                            isDeleted = false,
                            isPaid = true
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Category = 11,
                            CategoryId = 2,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1015),
                            Description = "Alaminuta",
                            TransactionDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1016),
                            UserId = 2,
                            Value = 172.34999999999999,
                            isDeleted = false,
                            isPaid = false
                        });
                });

            modelBuilder.Entity("TCC.Models.ExpenseCategory", b =>
                {
                    b.HasBaseType("TCC.Models.Category");

                    b.HasDiscriminator().HasValue("ExpenseCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(962),
                            Description = "Gym",
                            IconId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(964),
                            Description = "Clothing",
                            IconId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(965),
                            Description = "Education",
                            IconId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(965),
                            Description = "Pet",
                            IconId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(966),
                            Description = "Electronics",
                            IconId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(967),
                            Description = "Health",
                            IconId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(968),
                            Description = "Home",
                            IconId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(969),
                            Description = "Taxes",
                            IconId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(970),
                            Description = "Leisure",
                            IconId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(971),
                            Description = "Others",
                            IconId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(972),
                            Description = "Restaurant",
                            IconId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(974),
                            Description = "Services",
                            IconId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(974),
                            Description = "Supermarket",
                            IconId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(975),
                            Description = "Transportation",
                            IconId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(976),
                            Description = "Travel",
                            IconId = 15
                        });
                });

            modelBuilder.Entity("TCC.Models.Income", b =>
                {
                    b.HasBaseType("TCC.Models.Transaction");

                    b.Property<bool>("isReceived")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("Income");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            Category = 19,
                            CategoryId = 3,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1027),
                            Description = "Salário",
                            TransactionDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1027),
                            UserId = 1,
                            Value = 2000.0,
                            isDeleted = false,
                            isReceived = true
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 2,
                            Category = 16,
                            CategoryId = 4,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1029),
                            Description = "Premio",
                            TransactionDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(1029),
                            UserId = 2,
                            Value = 13.75,
                            isDeleted = false,
                            isReceived = false
                        });
                });

            modelBuilder.Entity("TCC.Models.IncomeCategory", b =>
                {
                    b.HasBaseType("TCC.Models.Category");

                    b.HasDiscriminator().HasValue("IncomeCategory");

                    b.HasData(
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(995),
                            Description = "Awards",
                            IconId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(996),
                            Description = "Gift",
                            IconId = 17
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(997),
                            Description = "Investments",
                            IconId = 18
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 9, 18, 1, 12, 26, DateTimeKind.Local).AddTicks(998),
                            Description = "Salary",
                            IconId = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
